// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// URLGetter is an autogenerated mock type for the URLGetter type
type URLGetter struct {
	mock.Mock
}

type URLGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *URLGetter) EXPECT() *URLGetter_Expecter {
	return &URLGetter_Expecter{mock: &_m.Mock}
}

// GetAllAliases provides a mock function with no fields
func (_m *URLGetter) GetAllAliases() ([]string, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllAliases")
	}

	var r0 []string
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]string, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// URLGetter_GetAllAliases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAliases'
type URLGetter_GetAllAliases_Call struct {
	*mock.Call
}

// GetAllAliases is a helper method to define mock.On call
func (_e *URLGetter_Expecter) GetAllAliases() *URLGetter_GetAllAliases_Call {
	return &URLGetter_GetAllAliases_Call{Call: _e.mock.On("GetAllAliases")}
}

func (_c *URLGetter_GetAllAliases_Call) Run(run func()) *URLGetter_GetAllAliases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *URLGetter_GetAllAliases_Call) Return(_a0 []string, _a1 error) *URLGetter_GetAllAliases_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *URLGetter_GetAllAliases_Call) RunAndReturn(run func() ([]string, error)) *URLGetter_GetAllAliases_Call {
	_c.Call.Return(run)
	return _c
}

// NewURLGetter creates a new instance of URLGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewURLGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *URLGetter {
	mock := &URLGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
